// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOhgoZ5zfH6S8NBgTWS06PYPZe4ZjNtyg',
    appId: '1:906760199257:web:30c7efb3a8585726d7e548',
    messagingSenderId: '906760199257',
    projectId: 'internship-e400f',
    authDomain: 'internship-e400f.firebaseapp.com',
    storageBucket: 'internship-e400f.appspot.com',
    measurementId: 'G-7LE49PD8Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl7y1KwRBbVUnxAZ6pGfgfLHf3PtR45U4',
    appId: '1:906760199257:android:4daf3f3839aa3a79d7e548',
    messagingSenderId: '906760199257',
    projectId: 'internship-e400f',
    storageBucket: 'internship-e400f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOD00kOSvaDCnY4XKFIqeaMa29Cpgm0Mw',
    appId: '1:906760199257:ios:281cca895bcf0e69d7e548',
    messagingSenderId: '906760199257',
    projectId: 'internship-e400f',
    storageBucket: 'internship-e400f.appspot.com',
    iosClientId: '906760199257-jok04op81nial4msha6aeem6uqh2k00l.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOD00kOSvaDCnY4XKFIqeaMa29Cpgm0Mw',
    appId: '1:906760199257:ios:8f589ec4a7b013ffd7e548',
    messagingSenderId: '906760199257',
    projectId: 'internship-e400f',
    storageBucket: 'internship-e400f.appspot.com',
    iosClientId: '906760199257-ge2pjqs6jutb7730ln8d80fkaqt6jek3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstproject.RunnerTests',
  );
}
